server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ddv12138/SpringCloudConfigrepository
          default-label: master
  #          search-paths: /website
  application:
    name: WebSite-config